stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: golang:1.14
          shellScript: |-
            mkdir -p /output
            mkdir -p /go/src/github.com/dualwave
            ln -s `pwd` /go/src/github.com/dualwave/nats
            cd /go/src/github.com/dualwave/nats/cmd/pub
            go build -o pub
            mv ./pub /output/
            cd /go/src/github.com/dualwave/nats/cmd/worker
            go build -o worker
            mv ./worker /output/

  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./PubDocker
          buildContext: .
          tag: example-nats-pub:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: registry.dualwave.dev
      - publishImageConfig:
          dockerfilePath: ./WorkerDocker
          buildContext: .
          tag: example-nats-sub:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: registry.dualwave.dev
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml
notification: {}
