stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: golang:1.14
          shellScript: |-
            mkdir -p /go/src/github.com/dualwave
            ln -s `pwd` /go/src/github.com/dualwave/nats
            cd /go/src/github.com/dualwave/nats
            go build -o bin/pub cmd/pub/main.go
            go build -o bin/worker cmd/sub/main.go
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./PubDocker
          buildContext: .
          tag: example-nats-pub:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: registry.dualwave.dev
        env:
          PLUGIN_STORAGE_PATH: /var/lib/docker/1
      - publishImageConfig:
          dockerfilePath: ./SubDocker
          buildContext: .
          tag: example-nats-sub:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: registry.dualwave.dev
        env:
          PLUGIN_STORAGE_PATH: /var/lib/docker/2
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml
notification: {}
